In [92]:
import sys
import numpy as np
sys.path.append("../")
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [95]:
#Creates word <-> int dirctionary 
from dhira.data.data_indexer import DataIndexer
#To read text data file
from dhira.data.dataset import TextDataset
#To parse the line in Text data file 
from dhira.data.features.pair_feature import PairFeature
#
from dhira.data.data_manager import DataManager
#For testing
from dhira.tests.common.test_case import DuplicateTestCase

from dhira.data.embedding_manager import EmbeddingManager

### Storyline
- Set the required `Feature Type` in `DataManager` and use datamanager instance to read the text dataset with `TextDataset` where the `Feature Type` is passed as a parameter.
- `TextDataset` reads the whole file and converts it into lines, which then parsed line by line by `Feature Type`
- The returned datatype is then used to fit the `Data Indexer`
- Convert the text feature to `Indexed Feature` with the trained `Data Indexer`

In [88]:
test = DuplicateTestCase()
test.setUp()
test.write_duplicate_questions_train_file()
test.write_vector_file()

### Pair Feature

In [3]:
#[id],[qid1],[qid2],[question1],[question2],[is_duplicate]
feature = PairFeature.read_from_line("0,0,1,question1 is similar to question2,question2 is similar to question1,1")

In [58]:
feature1 = PairFeature("this is an example", "this is another an example", 0)
feature2 = PairFeature("a a a a b", "b c c c", 1)
feature3 = PairFeature("this sentence can be similar", "this sentence might be have seen before", 1)
feature4 = PairFeature("Tensorflow is a Neural Network Library", "For Neural Netwrk Tensorflow is a good library", 1)

# feature5 = PairFeature.read_from_line("0","1","2","What is the step by step guide to invest in share market in india?","What is the step by step guide to invest in share market?","0")
# feature6 = PairFeature.read_from_line("1","3","4","What is the story of Kohinoor (Koh-i-Noor) Diamond?","What would happen if the Indian government stole the Kohinoor (Koh-i-Noor) diamond back?","0")
# feature7 = PairFeature.read_from_line("2","5","6","How can I increase the speed of my internet connection while using a VPN?","How can Internet speed be increased by hacking through DNS?","0")
# feature8 = PairFeature.read_from_line("3","7","8","Why am I mentally very lonely? How can I solve it?","Find the remainder when [math]23^{24}[/math] is divided by 24,23?","0")
# feature9 = PairFeature.read_from_line("4","9","10","Which one dissolve in water quikly sugar, salt, methane and carbon di oxide?","Which fish would survive in salt water?","0")
# feature10 = PairFeature.read_from_line("5","11","12","Astrology: I am a Capricorn Sun Cap moon and cap rising...what does that say about me?","I'm a triple Capricorn (Sun, Moon and ascendant in Capricorn) What does this say about me?","1")
# feature11 = PairFeature.read_from_line("6","13","14","Should I buy tiago?","What keeps childern active and far from phone and video games?","0")
# feature12 = PairFeature.read_from_line("7","15","16","How can I be a good geologist?","What should I do to be a great geologist?","1")
# feature13 = PairFeature.read_from_line("8","17","18","When do you use シ instead of し?","When do you use ""&"" instead of ""and""?","0")
# feature14 = PairFeature.read_from_line("9","19","20","Motorola (company): Can I hack my Charter Motorolla DCX3400?","How do I hack Motorola DCX3400 for free internet?","0")
# feature15 = PairFeature.read_from_line("10","21","22","Method to find separation of slits using fresnel biprism?","What are some of the things technicians can tell about the durability and reliability of Laptops and its components?","0")
# feature16 = PairFeature.read_from_line("11","23","24","How do I read and find my YouTube comments?","How can I see all my Youtube comments?","1")
# feature17 = PairFeature.read_from_line("12","25","26","What can make Physics easy to learn?","How can you make physics easy to learn?","1")
# feature18 = PairFeature.read_from_line("13","27","28","What was your first sexual experience like?","What was your first sexual experience?","1")
# feature19 = PairFeature.read_from_line("14","29","30","What are the laws to change your status from a student visa to a green card in the US, how do they compare to the immigration laws in Canada?","What are the laws to change your status from a student visa to a green card in the US? How do they compare to the immigration laws in Japan?","0")
# feature20 = PairFeature.read_from_line("15","31","32","What would a Trump presidency mean for current international master’s students on an F1 visa?","How will a Trump presidency affect the students presently in US or planning to study in US?","1")
# feature21 = PairFeature.read_from_line("16","33","34","What does manipulation mean?","What does manipulation means?","1")
# feature22 = PairFeature.read_from_line("17","35","36","Why do girls want to be friends with the guy they reject?","How do guys feel after rejecting a girl?","0")
# feature23 = PairFeature.read_from_line("18","37","38","Why are so many Quora users posting questions that are readily answered on Google?","Why do people ask Quora questions which can be answered easily by Google?","1")
# feature24 = PairFeature.read_from_line("19","39","40","Which is the best digital marketing institution in banglore?","Which is the best digital marketing institute in Pune?","0")
# feature25 = PairFeature.read_from_line("20","41","42","Why do rockets look white?","Why are rockets and boosters painted white?","1")
# feature26 = PairFeature.read_from_line("21","43","44","What's causing someone to be jealous?","What can I do to avoid being jealous of someone?","0")
# feature27 = PairFeature.read_from_line("22","45","46","What are the questions should not ask on Quora?","Which question should I ask on Quora?","0")
# feature28 = PairFeature.read_from_line("23","47","48","How much is 30 kV in HP?","Where can I find a conversion chart for CC to horsepower?","0")
# feature29 = PairFeature.read_from_line("24","49","50","What does it mean that every time I look at the clock the numbers are the same?","How many times a day do a clock’s hands overlap?","0")

In [6]:
feature.first_sentence_str

'question1 is similar to question2'

In [7]:
feature.second_sentence_str

'question2 is similar to question1'

In [8]:
feature.label

1

In [9]:
feature.label_mapping

{0: [1, 0], 1: [0, 1], None: None}

In [10]:
feature.first_sentence_tokenized

{'characters': [['q', 'u', 'e', 's', 't', 'i', 'o', 'n', '1'],
  ['i', 's'],
  ['s', 'i', 'm', 'i', 'l', 'a', 'r'],
  ['t', 'o'],
  ['q', 'u', 'e', 's', 't', 'i', 'o', 'n', '2']],
 'words': ['question1', 'is', 'similar', 'to', 'question2']}

In [11]:
feature.second_sentence_tokenized

{'characters': [['q', 'u', 'e', 's', 't', 'i', 'o', 'n', '2'],
  ['i', 's'],
  ['s', 'i', 'm', 'i', 'l', 'a', 'r'],
  ['t', 'o'],
  ['q', 'u', 'e', 's', 't', 'i', 'o', 'n', '1']],
 'words': ['question2', 'is', 'similar', 'to', 'question1']}

### Dataset

In [5]:
dataset = TextDataset([feature1, feature2, feature3, feature4])

### Data Indexer

In [31]:
data_indexer = DataIndexer()
data_indexer.fit_word_dictionary(dataset, min_count=1)

100%|██████████| 4/4 [00:00<00:00, 2875.27it/s]


In [32]:
data_indexer.words_in_index()

dict_keys(['@@PADDING@@', '@@UNKOWN@@', 'a', 'is', 'this', 'c', 'an', 'b', 'be', 'example', 'library', 'neural', 'sentence', 'tensorflow', 'another', 'before', 'can', 'for', 'good', 'have', 'might', 'network', 'netwrk', 'seen', 'similar'])

In [33]:
data_indexer.get_vocab_size()

25

In [34]:
word_index = data_indexer.add_word_to_index("dhira")

In [35]:
data_indexer.words_in_index()

dict_keys(['@@PADDING@@', '@@UNKOWN@@', 'a', 'is', 'this', 'c', 'an', 'b', 'be', 'example', 'library', 'neural', 'sentence', 'tensorflow', 'another', 'before', 'can', 'for', 'good', 'have', 'might', 'network', 'netwrk', 'seen', 'similar', 'dhira'])

### Indexed Feature

In [15]:
indexed_feature = feature.to_indexed_feature(data_indexer)

In [ ]:
indexed_feature.get_int_word_indices

In [ ]:
dataset.features

### DataManager

In [60]:
data_manager = DataManager(PairFeature)
data_manager.set_pickle_folder(".")

In [61]:
get_train_gen, train_size = data_manager.get_train_data_from_file([DuplicateTestCase.TRAIN_FILE])

2017-07-17 20:09:10,085 - INFO - dhira.data.data_manager - Reusing the pickle file train_data.p.
2017-07-17 20:09:10,087 - INFO - dhira.data.data_manager - Instance max lengths {'num_sentence_words': 2, 'num_word_characters': 12}
2017-07-17 20:09:10,088 - INFO - dhira.data.data_manager - Padding lengths to length: {'num_sentence_words': 2, 'num_word_characters': 12}


In [62]:
train_size

3

In [65]:
train_gen = get_train_gen()

In [66]:
train_gen.__next__()

((array([2, 0], dtype=int32), array([3, 4], dtype=int32)), (array([1, 0]),))

In [67]:
train_gen.__next__()

((array([5, 0], dtype=int32), array([6, 0], dtype=int32)), (array([0, 1]),))

In [68]:
train_gen.__next__()

((array([7, 0], dtype=int32), array([8, 0], dtype=int32)), (array([1, 0]),))

In [74]:
data_manager = DataManager(PairFeature)
data_manager.set_pickle_folder(".")

In [75]:
get_train_gen, train_size = data_manager.get_train_data_from_file(
            [DuplicateTestCase.TRAIN_FILE], mode="character")

2017-07-17 20:15:42,090 - INFO - dhira.data.data_manager - Processing the train data file for first time
2017-07-17 20:15:42,091 - INFO - dhira.data.data_manager - Getting training data from ['./TMP_TEST/train_file']
2017-07-17 20:15:42,092 - INFO - dhira.data.dataset - Reading files ['./TMP_TEST/train_file'] to a list of lines.
100%|██████████| 3/3 [00:00<00:00, 7767.23it/s]
2017-07-17 20:15:42,097 - INFO - dhira.data.dataset - Creating list of <class 'dhira.data.features.pair_feature.PairFeature'> features from list of lines.
100%|██████████| 3/3 [00:00<00:00, 1365.93it/s]
2017-07-17 20:15:42,105 - INFO - dhira.data.dataset - Finished reading dataset; label counts: [(0, 2), (1, 1)]
2017-07-17 20:15:42,106 - INFO - dhira.data.data_manager - Fitting data indexer word dictionary, min_count is 1.
2017-07-17 20:15:42,108 - INFO - dhira.data.data_indexer - Fitting word dictionary with min count of 1
100%|██████████| 3/3 [00:00<00:00, 3788.89it/s]
2017-07-17 20:15:42,113 - INFO - dhira.data

In [76]:
train_gen = get_train_gen()

In [77]:
train_gen.__next__()

((array([[ 6,  9,  2,  7,  8,  3,  5,  4, 10,  0,  0,  0],
         [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0]], dtype=int32),
  array([[ 6,  9,  2,  7,  8,  3,  5,  4, 11,  0,  0,  0],
         [ 6,  9,  2,  7,  8,  3,  5,  4, 12, 19, 17, 18]], dtype=int32)),
 (array([1, 0]),))

In [78]:
train_gen.__next__()

((array([[ 6,  9,  2,  7,  8,  3,  5,  4, 13,  0,  0,  0],
         [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0]], dtype=int32),
  array([[ 6,  9,  2,  7,  8,  3,  5,  4, 14,  0,  0,  0],
         [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0]], dtype=int32)),
 (array([0, 1]),))

In [79]:
train_gen.__next__()

((array([[ 6,  9,  2,  7,  8,  3,  5,  4, 15,  0,  0,  0],
         [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0]], dtype=int32),
  array([[ 6,  9,  2,  7,  8,  3,  5,  4, 16,  0,  0,  0],
         [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0]], dtype=int32)),
 (array([1, 0]),))

In [81]:
data_manager = DataManager(PairFeature)
data_manager.set_pickle_folder(".")

In [82]:
get_train_gen, train_size = data_manager.get_train_data_from_file(
            [DuplicateTestCase.TRAIN_FILE], mode="word+character")

2017-07-17 20:17:18,493 - INFO - dhira.data.data_manager - Processing the train data file for first time
2017-07-17 20:17:18,494 - INFO - dhira.data.data_manager - Getting training data from ['./TMP_TEST/train_file']
2017-07-17 20:17:18,495 - INFO - dhira.data.dataset - Reading files ['./TMP_TEST/train_file'] to a list of lines.
100%|██████████| 3/3 [00:00<00:00, 11018.31it/s]
2017-07-17 20:17:18,499 - INFO - dhira.data.dataset - Creating list of <class 'dhira.data.features.pair_feature.PairFeature'> features from list of lines.
100%|██████████| 3/3 [00:00<00:00, 1604.35it/s]
2017-07-17 20:17:18,505 - INFO - dhira.data.dataset - Finished reading dataset; label counts: [(0, 2), (1, 1)]
2017-07-17 20:17:18,506 - INFO - dhira.data.data_manager - Fitting data indexer word dictionary, min_count is 1.
2017-07-17 20:17:18,508 - INFO - dhira.data.data_indexer - Fitting word dictionary with min count of 1
100%|██████████| 3/3 [00:00<00:00, 6519.64it/s]
2017-07-17 20:17:18,512 - INFO - dhira.dat

In [83]:
train_gen = get_train_gen()

In [84]:
train_gen.__next__()

((array([2, 0], dtype=int32),
  array([[ 6,  9,  2,  7,  8,  3,  5,  4, 10,  0,  0,  0],
         [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0]], dtype=int32),
  array([3, 4], dtype=int32),
  array([[ 6,  9,  2,  7,  8,  3,  5,  4, 11,  0,  0,  0],
         [ 6,  9,  2,  7,  8,  3,  5,  4, 12, 19, 17, 18]], dtype=int32)),
 (array([1, 0]),))

In [85]:
train_gen.__next__()

((array([5, 0], dtype=int32),
  array([[ 6,  9,  2,  7,  8,  3,  5,  4, 13,  0,  0,  0],
         [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0]], dtype=int32),
  array([6, 0], dtype=int32),
  array([[ 6,  9,  2,  7,  8,  3,  5,  4, 14,  0,  0,  0],
         [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0]], dtype=int32)),
 (array([0, 1]),))

In [86]:
train_gen.__next__()

((array([7, 0], dtype=int32),
  array([[ 6,  9,  2,  7,  8,  3,  5,  4, 15,  0,  0,  0],
         [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0]], dtype=int32),
  array([8, 0], dtype=int32),
  array([[ 6,  9,  2,  7,  8,  3,  5,  4, 16,  0,  0,  0],
         [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0]], dtype=int32)),
 (array([1, 0]),))

### Embedding Manager

In [102]:
data_indexer = DataIndexer()
data_indexer.is_fit = True
data_indexer.add_word_to_index("word1")

2

In [103]:
data_indexer.add_word_to_index("word2")

3

In [104]:
embedding_dict = {"word1": np.array([5.1, 7.2, -0.2]),
                   "word2": np.array([0.8, 0.1, 0.9])}

In [105]:
embedding_manager = EmbeddingManager(data_indexer)

In [106]:
embed_mat = embedding_manager.get_embedding_matrix(3, pretrained_embeddings_file_path=DuplicateTestCase.VECTORS_FILE)

2017-07-17 20:30:55,458 - INFO - dhira.data.embedding_manager - Reading pretrained embeddings from ./TMP_TEST/vectors_file
2it [00:00, 10305.42it/s]


In [107]:
embed_mat

array([[ 0.00488135,  0.02151894,  0.01027634],
       [ 0.00448832, -0.00763452,  0.01458941],
       [ 0.        ,  1.10000002,  0.2       ],
       [ 0.1       ,  0.40000001, -4.        ]])