In [1]:
import tensorflow as tf

In [2]:
sess = tf.InteractiveSession()

In [3]:
x = tf.Variable([1.0, 2.0])
a = tf.constant([3.0, 3.0])

# Initialize 'x' using the run() method of its initializer op.
x.initializer.run()

# Add an op to subtract 'a' from 'x'.  Run it and print the result
sub = tf.subtract(x, a)
print(sub.eval())
# ==> [-2. -1.]
# Close the Session when we're done.


[ nan  nan]


In [4]:
# sess.close()

In [18]:
# Create a Variable, that will be initialized to the scalar value 0.
state = tf.Variable(0, name="counter")

# Create an Op to add one to `state`.

one = tf.constant(1)
new_value = tf.add(state, one)
update = tf.assign(state, new_value)
g = tf.cast(tf.greater([0.1,0.2,0.5,0.51, 0.8],0.49),'int32')
ceil = tf.ceil([0.1,0.2,0.5,0.8])
floor = tf.floor([0.1,0.2,0.5,0.8])

sub = tf.subtract(1.0, [1,2,3,0.5,0.1, 0.9])
# Variables must be initialized by running an `init` Op after having
# launched the graph.  We first have to add the `init` Op to the graph.

# Launch the graph and run the ops.
with tf.Session() as sess:
    # Run the 'init' op
    sess.run(tf.global_variables_initializer())
    # Print the initial value of 'state'
    print(sess.run(state))
    print(sess.run(g))
    print(sess.run(ceil))
    print(sess.run(floor))
    print(sess.run(sub))
    # Run the op that updates 'state' and print 'state'.
    for _ in range(3):
        sess.run(update)
        print(sess.run(state))

0
[0 0 1 1 1]
[ 1.  1.  1.  1.]
[ 0.  0.  0.  0.]
[ 0.         -1.         -2.          0.5         0.89999998  0.10000002]
1
2
3
