# Normalization
Zero mean with unit variance/standard deviation

$$
X = \frac{(X - mean)}{Standard Deviation}
$$

In [5]:
import numpy as np

eg_array = 5 + (np.random.randn(5, 5) * 2)
eg_array



array([[ 5.4756477 ,  4.09979023,  3.54074881,  4.38810065,  4.59140697],
       [ 2.63384151,  2.85166603,  6.50827527,  4.97615907,  1.28873739],
       [ 5.26288173,  4.88670661,  8.70436009,  1.06202372,  4.31384121],
       [ 5.01601644,  0.14986963,  5.18111185,  5.48800217,  1.61974808],
       [ 0.12276729, -0.66970105,  3.97116118,  6.71258957,  4.6058369 ]])

In [6]:
normed = (eg_array - eg_array.mean(axis=0)) / eg_array.std(axis=0)

In [7]:
normed.mean(axis=0)

array([ -2.22044605e-16,  -1.33226763e-16,   2.22044605e-17,
         0.00000000e+00,   1.55431223e-16])

In [8]:
normed.std(axis=0)

array([ 1.,  1.,  1.,  1.,  1.])